version: '3.7'
services:
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - geometric
    volumes:
      - ./neo4j/conf:/conf
      - geometric_neo4j:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment: 
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
  jupyter:
    container_name: jupyter
    build: ./pytorch_geometric/
    volumes:
      - ./pytorch_geometric/:/notebook/
    ports:
      - 8888:8888
    networks:
      - geometric
    depends_on:
      - neo4j

volumes:
  geometric_neo4j:
networks:
  geometric:
